@echo off
REM Omnisystem Main Launcher
REM Generated by Omnisystem Launcher Creator
cd /d "Z:\Projects\Omnisystem"
"Z:\Projects\Omnisystem\titan-bootstrap\target\release\titan-bootstrap.exe" "titan/launcher/omni_launcher.ti" --run %*
