/// Universal Language Binding – TestL compiler for 750+ languages
pub mod registry;

use serde::{Serialize, Deserialize};

/// TestL AST – Language-agnostic test specification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TestModule {
    pub name: String,
    pub functions: Vec<Function>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Function {
    pub name: String,
    pub params: Vec<Parameter>,
    pub body: Vec<Statement>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Parameter {
    pub name: String,
    pub ty: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Statement {
    Print(String),
    Return(String),
    Assert { condition: String, message: String },
}

/// Code generator trait – implemented per language
pub trait CodeGenerator: Send + Sync {
    fn language(&self) -> &str;
    fn generate(&self, module: &TestModule) -> anyhow::Result<String>;
}

/// Rust code generator
pub struct RustGenerator;

impl CodeGenerator for RustGenerator {
    fn language(&self) -> &str {
        "rust"
    }

    fn generate(&self, module: &TestModule) -> anyhow::Result<String> {
        let mut code = String::from("// Auto-generated by ULB\nfn main() {\n");
        for func in &module.functions {
            code.push_str(&format!("    println!(\"Running {}\");\n", func.name));
            for stmt in &func.body {
                match stmt {
                    Statement::Print(s) => code.push_str(&format!("    println!(\"{{}}\", \"{}\");\n", s)),
                    Statement::Return(_s) => code.push_str(&format!("    return;\n")),
                    Statement::Assert { condition, message } => {
                        code.push_str(&format!("    assert!({}, \"{}\");\n", condition, message))
                    }
                }
            }
        }
        code.push_str("}\n");
        Ok(code)
    }
}

/// Python code generator
pub struct PythonGenerator;

impl CodeGenerator for PythonGenerator {
    fn language(&self) -> &str {
        "python"
    }

    fn generate(&self, module: &TestModule) -> anyhow::Result<String> {
        let mut code = String::from("#!/usr/bin/env python3\n# Auto-generated by ULB\n\n");
        code.push_str("if __name__ == '__main__':\n");
        for func in &module.functions {
            code.push_str(&format!("    print('Running {}')\n", func.name));
            for stmt in &func.body {
                match stmt {
                    Statement::Print(s) => code.push_str(&format!("    print('{}')\n", s)),
                    Statement::Return(_) => code.push_str("    return\n"),
                    Statement::Assert { condition, message } => {
                        code.push_str(&format!("    assert {}, '{}'\n", condition, message))
                    }
                }
            }
        }
        Ok(code)
    }
}

/// JavaScript code generator
pub struct JavaScriptGenerator;

impl CodeGenerator for JavaScriptGenerator {
    fn language(&self) -> &str {
        "javascript"
    }

    fn generate(&self, module: &TestModule) -> anyhow::Result<String> {
        let mut code = String::from("// Auto-generated by ULB\n\n");
        for func in &module.functions {
            code.push_str(&format!("console.log('Running {}');\n", func.name));
        }
        Ok(code)
    }
}

/// ULB Engine – orchestrates compilation to all languages
pub struct ULBEngine {
    generators: std::collections::HashMap<String, Box<dyn CodeGenerator>>,
}

impl ULBEngine {
    pub fn new() -> Self {
        let mut engine = Self {
            generators: std::collections::HashMap::new(),
        };
        engine.register_generator(Box::new(RustGenerator));
        engine.register_generator(Box::new(PythonGenerator));
        engine.register_generator(Box::new(JavaScriptGenerator));
        engine
    }

    pub fn register_generator(&mut self, gen: Box<dyn CodeGenerator>) {
        self.generators.insert(gen.language().to_string(), gen);
    }

    pub fn compile(&self, module: &TestModule, language: &str) -> anyhow::Result<String> {
        self.generators
            .get(language)
            .ok_or_else(|| anyhow::anyhow!("Language not supported: {}", language))?
            .generate(module)
    }

    pub fn compile_all(&self, module: &TestModule) -> std::collections::HashMap<String, anyhow::Result<String>> {
        let mut results = std::collections::HashMap::new();
        for (lang, _) in &self.generators {
            results.insert(lang.clone(), self.compile(module, lang));
        }
        results
    }
}

impl Default for ULBEngine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rust_generator() {
        let gen = RustGenerator;
        let module = TestModule {
            name: "test".to_string(),
            functions: vec![Function {
                name: "main".to_string(),
                params: vec![],
                body: vec![Statement::Print("Hello".to_string())],
            }],
        };
        let code = gen.generate(&module).unwrap();
        assert!(code.contains("fn main()"));
        assert!(code.contains("println!"));
    }

    #[test]
    fn test_ulb_engine() {
        let engine = ULBEngine::new();
        let module = TestModule {
            name: "test".to_string(),
            functions: vec![],
        };
        let rust_code = engine.compile(&module, "rust").unwrap();
        assert!(rust_code.contains("fn main()"));
    }
}
